### ISSUE TITLE
(Serverless initiative): test Prisma error messages in unsupported systems

### ISSUE THREAD

**Issue by jkomyno** [prisma/ecosystem-tests#3332]
Prisma may throw a number of [different error messages](https://github.com/prisma/prisma/blob/3077f505d317e3b3f1d2b20682f6d0273f5c59c4/packages/internals/src/engine-commands/queryEngineCommons.ts#L83) when loading the Prisma Engines fails. Although we already attempt to provide meaningful user-facing explanations of what went wrong, we should strive to be more precise.

We should thus add some ecosystem-tests that try to install and run Prisma on scenarios where we know it would fail.

Relevant unsupported systems we should test the new conditional error messages on:
- [x] Linux Alpine on `arm64` arch (only `x86_64` is supported for Linux Alpine, see https://github.com/prisma/prisma/issues/8478)
- [x] Distroless without `libz.so.1` (see [this comment](https://github.com/prisma/prisma/issues/16205#issuecomment-1371456830)) 
- [x] Debian Buster without any `libssl` version installed (see [this comment](https://github.com/prisma/prisma/issues/16182#issuecomment-1371283457))
- [x] Linux Alpine 3.17 on `x86_64` arch with `binaryTargets: ["linux-musl"]` (it ships `openssl-3.0.x`, but will try to dynamically load `openssl-1.1.x`, see https://github.com/prisma/prisma/issues/16553)
- [ ] ~~Assert failures causes by Prisma not being able to load its engines~~.

**Comment by janpio** [comment]
This is probably not something that should be run with _every_ version. But it totally makes sense as a manual thing we can run.

**Comment by mcbethio** [comment]
Folks, can we fix the milestone on this issue please. 4.9.0 has already sailed.

**Comment by jkomyno** [comment]
Note: we tried assertions in https://github.com/prisma/prisma/pull/17762, but they didn't make it to the release due to bundling issues with `jest.spyOn`. We did manual testing using the setup from `ecosystem-tests / docker` on an integration release for the time being.
